
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.App.OnStartup(System.Windows.StartupEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Commands.ReactiveCommand`1.Dispose")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.BootStrapper.Start")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Models.DisposableObject.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Services.ColumnsService.#ctor(Simple.Wpf.DataGrid.Services.ISettingsService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Services.DiagnosticsService.#ctor(Simple.Wpf.DataGrid.Services.IIdleService,Simple.Wpf.DataGrid.Services.ISchedulerService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Services.HeartbeatService.#ctor(System.TimeSpan,Simple.Wpf.DataGrid.Services.ISchedulerService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Services.OverlayService.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Services.TabularDataGenerator.CreateInitialSnapshot~System.Collections.Generic.IEnumerable{Simple.Wpf.DataGrid.Models.DynamicData}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Services.SettingsService.#ctor(Simple.Wpf.DataGrid.Services.ISchedulerService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Services.IdleService.#ctor(Simple.Wpf.DataGrid.Services.ISchedulerService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Services.GesturesService.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Services.CultureService.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Services.TabularDataService.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Extensions.MemoryExtensions.WorkingSetPrivateAsString(Simple.Wpf.DataGrid.Models.Memory)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "HeapAnalyzerStringConcatRule:Implicit string concatenation allocation", Justification = "<Pending>", Scope = "member", Target = "~M:Simple.Wpf.DataGrid.Extensions.MemoryExtensions.ManagedAsString(Simple.Wpf.DataGrid.Models.Memory)~System.String")]

